### ISSUE TITLE
heredoc manager: get_filename함수 동작방식

### ISSUE THREAD

**Issue by geneeol** [earthicko/42cursus-minishell#2]
heredoc manager (1/15)
- getfilename함수 다음과 같이 제안.
어차피 히얼독파일에서 open, read할거면 순차적으로 호출될테니, getfilename도 순차적으로 호출 됨. 
이제 static변수로 cursor를 하나 만들어서 함수 호출할 때마다 cursor를 1씩 움직여서 이를 doc_id로 쓰는거지
(리다이렉션 관련 배열 만들 때 몇번째 히얼독인지에 대한 정보가 따로 없음)

문제는 저렇게 수정한다면 heredoc_read에서도 get_file_name을 호출해서 조금 꼬여버림.

**Comment by earthicko** [comment]
`heredoc_get_next_filename()` 추가함
