### ISSUE TITLE
signal입력으로 종료될 경우, exit status가 일치하지 않음.

### ISSUE THREAD

**Issue by geneeol** [earthicko/42cursus-minishell#20]
시그널로 프로세스가 종료되는 경우 exit status 128 + N  (시그널 번호)로 처리되어야 함.
(현재 sleep 10, ctrl + c 입력시 exit status 0나옴. bash는 130)
sa_handler 함수를 별도로 만들어서 exit status에 대한 처리가 필요해보임.

**Comment by earthicko** [comment]
96a67abd에서 해결

```c
if (last_cmd == wait(&status))
{
	if (WIFSIGNALED(status))
		exit_status = WTERMSIG(status) + 128;
	else
		exit_status = WEXITSTATUS(status);
}
```
