### ISSUE TITLE
명령줄에서 ctrl+c입력시, exit status가 일치하지 않음. (부모 프로세스)

### ISSUE THREAD

**Issue by geneeol** [earthicko/42cursus-minishell#25]
bash에서 명령어 엔터치기 전, ctrl + c 입력하면 새 프롬프트가 출력됨. 
이 때 echo $? 입력시 1 출력
우리 쉘에서는 0으로 출력됨.

해당 내용은 메뉴얼에 따로 명시된 내용은 없어보임. 그래서 수정여부는 선택사항일듯
만약 고칠거라면 sighandler_int_interactive 함수에서 exit status만 1로 업데이트 해주면 될 듯.

**Comment by earthicko** [comment]
오 굿발견

**Comment by earthicko** [comment]
16d14276에서 해결
