### ISSUE TITLE
export 및 env의 미세한 차이

### ISSUE THREAD

**Issue by geneeol** [earthicko/42cursus-minishell#32]
bash에선
export var후
export | grep var 하면 var이 잡힘.
그러나 env | grep var 하면 잡히지 않음.
>------------<
우리 쉘에선
export var하면 우선 환경변수에 등록되지 않음 (로직상 =이 있을 때만 할당시도)
따라서 var자체가 변수로 등록되진 않음.

고치지 않아도 된다고 생각함. 명세에 이와 관련된 내용이 표시돼 있지 않은듯.

**Comment by earthicko** [comment]
이것은 시간이 되면 고치는게 나아보인다
환경 변수에 set 상태가 있다는걸 간과한 결과이기 때문

변수가 존재하면 `export`에서는 무조건 나오지만 변수가 존재해도 값이 set가 안되어 있으면 `fork()`할 때 `envp`로 넘겨주지 않고 `env`에 안나옴 (물론 빈 문자열로 값을 set하면 잘 나온다)

`export var` 하면 `var`라는 변수가 생기지만 값이 set 되지 않아서
- `export` -> `declare -x var`
- `env` -> 표시되지 않음

`export var=` 하면 `var`라는 변수를 만들고 값을 `""`로 설정해서
- `export` -> `declare -x var=""`
- `env` -> `var=`

### 해결책

envmanager의 내부 엔트리 구조체에 `set` 속성 추가
set를 안 하고 엔트리만 생성하는 `createvar` 메소드 추가, `setval`을 호출하면 `createvar`부터 먼저 하도록 변경, `setval`이 끝나면 비로소 엔트리에 set 속성 설정
`export`시 파라미터가 `name` 꼴이면 `createvar`, `name=val` 꼴이면 `setval`을 하도록 변경
set가 안 된 변수는 `getenvp`를 호출해도 `envp` 문자열에 포함되지 않도록 함

**Comment by earthicko** [comment]
[eee772d4](https://github.com/earthicko/42cursus-minishell/commit/eee772d465d330d9528c176d8b377597adb759bc)에서 구현
